spring:
  profiles:
    active: local

  thymeleaf:
    prefix: file:src/main/resources/templates/
#    prefix: classpath:/templates/
    suffix: .html
    resources:
        static-locations: file:src/main/resources/static/

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true

  datasource:
    url: jdbc:h2:file:./temp/yjc-temp-database
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
      org.hibernate.orm.jdbc.bind: trace
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
